version = "2613.0.0"
author = "disruptek"
description = "Amazon Web Services (AWS) APIs"
license = "MIT"
requires "nim >= 0.20.0"
requires "sigv4 >= 1.0.4"
requires "https://github.com/disruptek/rest.git >= 1.0.0"
requires "https://github.com/disruptek/openapi.git >= 3.1.3"
requires "npeg >= 0.22.2"

srcDir = "src"
