version = "2543.0.0"
author = "disruptek"
description = "Amazon Web Services (AWS) APIs"
license = "MIT"
requires "nim >= 0.20.0"
requires "openapi >= 3.1.0"
requires "sigv4 >= 1.0.2"
requires "https://github.com/disruptek/rest.git >= 1.0.0"

srcDir = "src"
